### PR TITLE
Change name to Price Tracker

### PR DESCRIPTION
**Pull request by biancadanforth**
@javaun , @chuckharmston Requesting your approval on the following noteworthy items:
- [x] Leave the existing telemetry event category unchanged, `'extension.price_wise'` for continuity.
- [x] Remove the [Feedback survey](https://qsurvey.mozilla.com/s3/price-wise)
- Alternatives (feedback form):
  - Teon updates the URL/survey page and we update it here in the extension.
  - We leave the survey and UI as-is
- [x] Change the privacy policy URL to https://addons.mozilla.org/en-US/firefox/addon/price-tracker/privacy/. This requires changing the AMO URL to https://addons.mozilla.org/en-US/firefox/addon/price-tracker, which does not redirect from https://addons.mozilla.org/en-US/firefox/addon/price-wise .

Screen Shot 2019-03-19 at 9 01 17 PM

Screen Shot 2019-03-19 at 9 09 16 PM

Screen Shot 2019-03-19 at 9 13 45 PM

---

Find and replace all instances of "Price Wise", "price-wise" and "price_wise" (case insensitive) with the following exceptions:
* The telemetry event category, 'extension.price_wise' for continuity.
* The survey URLs (for [feedback](https://qsurvey.mozilla.com/s3/price-wise) linked to in the popup and the now flagged off [UR study](https://qsurvey.mozilla.com/s3/Price-Wise-Research-Study)).

Note: Updating the name of the project in `package.json` and calling `npm install` also triggered adding an additional [`optional`](https://docs.npmjs.com/files/package-lock.json#optional) key in `package-lock.json` for some devDeps.

### CODE REVIEW

**Comment by clouserw** [comment]
I think it looks fine, but Chuck will be a better reviewer than me for this code so flagging him

**Comment by biancadanforth** [comment]
@javaun , @chuckharmston : In light of the urgency of this change request from Mika, I would ask that you please let me know by the end of the day tomorrow if at all possible (Wednesday, 3/20); otherwise my plan will be to:
* Leave the telemetry category as-is `'extension.price_wise'`
* Remove the survey URL/UI entirely (I will try and enlist a QA resource to help me test this)
* Leave the privacy policy URL as-is (and thus keep the original AMO URL from which it is derived, https://addons.mozilla.org/en-US/firefox/addon/price-wise)

**Comment by chuckharmston** [comment]
My thoughts:

- It would certainly be desirable to leave the telemetry event category. I'll check with Mika to make sure that's okay.
- Let's remove the survey; it's not particularly useful if nobody is actively maintaining.
- As long as the link from the add-on works, I see no issues with changing the privacy policy link.

**Comment by chuckharmston** [comment]
Filed https://github.com/mozilla/testpilot/issues/4045 to make sure the Test Pilot site gets updated. @clouserw, can you make sure somebody is able to work on that?

**Comment by biancadanforth** [comment]
Thanks @chuckharmston for the quick feedback! Just one clarification for you:
> As long as the link from the add-on works, I see no issues with changing the privacy policy link.

Just to confirm, since the privacy policy page's URL is based on the extension's AMO page URL, you would rather we update the AMO page URL from https://addons.mozilla.org/en-US/firefox/addon/price-wise/ to https://addons.mozilla.org/en-US/firefox/addon/price-tracker/ ? Per jorgev, it is not possible to redirect from the former to the latter.

**Comment by chuckharmston** [comment]
Yeah, that seems like the sort of thing that _is_ necessary for us to do. Since this is effectively a dormant project, I'm not too concerned about the consequences of the URL change, especially since there's still a link on Test Pilot's site that can be changed.

**Comment by biancadanforth** [comment]
Got an AMO pre-review approval over e-mail from @wagnerand , so going to merge.

**Comment by pdehaan** [comment]
Any ETA on when the add-on will be published at https://addons.mozilla.org/en-US/firefox/addon/price-tracker/?

**Comment by marniepw** [comment]
@pdehaan it's been submitted to AMO for review. Fingers crossed...

**Comment by biancadanforth** [comment]
It was published about an hour ago.

**Comment by pdehaan** [comment]
> Filed [mozilla/testpilot#4045](https://github.com/mozilla/testpilot/issues/4045) to make sure the Test Pilot site gets updated. @clouserw, can you make sure somebody is able to work on that?

This should be in production now, per https://github.com/mozilla/testpilot/issues/4045#issuecomment-475386990

**Pull request merged**
